ota:
api:
logger:
  # important because we are using uart0
  # to communicate with Tuya MCU
  baud_rate: 0

# Fill in your own wifi settings
wifi: !secret wifi

esphome:
  name: curtain
  platform: ESP8266
  board: esp01_1m
  includes:
    - curtain.h
uart:
  - id: com_1
    tx_pin: GPIO01
    rx_pin: GPIO03
    baud_rate: 9600

globals:
  - id: cover_open
    type: bool
    restore_value: yes
    initial_value: "false"
  - id: cover_reversed
    type: bool
    restore_value: yes
    initial_value: "false"
  - id: cover_position
    type: float
    restore_value: yes
    initial_value: "0"

cover:
  - platform: custom
    lambda: |-
      auto curtain = new CustomCurtain();
      App.register_component(curtain);
      return {curtain};
    covers:
      - name: ${area} Curtain
        device_class: blind
#         device_class: curtain
    
